#spring.application.name=tickets
server:
    port: 0
spring:
    application:
        name: ticket-api
eureka:
    instance:
        prefer-ip-address: true
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
